#!/bin/bash
# 推文配图: 记住项目上下文

echo ""
echo -e "${BG_BLUE}${WHITE}  ReX CLI - 记住项目上下文  ${NC}"
echo ""
echo -e "${GRAY}─────────────────────────────────────────────────────────${NC}"
echo ""
echo -e "${GREEN}➜${NC} ${WHITE}rex run --workspace myapp --prompt \"添加用户认证\""
echo ""
echo -e "${CYAN}[Memory]${NC} 📚 加载项目上下文..."
echo -e "   ├─ 技术栈: Next.js + PostgreSQL + Prisma"
echo -e "   ├─ 编码规范: TypeScript strict + ESLint"
echo -e "   └─ 偏好: 使用 tRPC 而非 REST"
echo ""
echo -e "${CYAN}[1/3]${NC} ⚡ 生成代码..."
echo -e "   ✓ auth/middleware.ts (new)"
echo -e "   ✓ auth/jwt.ts (new)"
echo ""
echo -e "${CYAN}[2/3]${NC} 🧪 验证..."
echo -e "   ✓ TypeScript 编译通过"
echo -e "   ✓ ESLint 检查通过"
echo ""
echo -e "${CYAN}[3/3]${NC} 💾 保存变更..."
echo -e "   ✓ 记住: 添加了 JWT 认证模块"
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✓ 下次运行时，ReX 会记住这个模块${NC}"
echo ""
echo -e "${GRAY}─────────────────────────────────────────────────────────${NC}"
echo ""
