#!/bin/bash
# 推文配图: 多Provider切换

echo ""
echo -e "${BG_BLUE}${WHITE}  ReX CLI - 智能切换 LLM Provider  ${NC}"
echo ""
echo -e "${GRAY}─────────────────────────────────────────────────────────${NC}"
echo ""
echo -e "${GREEN}➜${NC} ${WHITE}rex run --prompt \"分析这段代码\" --model default"
echo ""
echo -e "${CYAN}🤖 Provider: OpenAI (o3-mini)${NC}"
echo -e "${YELLOW}   💰 成本: $0.002 | ⏱️ 延迟: 1.2s"
echo ""
echo -e "${RED}⚠️  速率限制触发，切换 Provider...${NC}"
echo ""
echo -e "${CYAN}🤖 Provider: Anthropic (claude-3-haiku)${NC}"
echo -e "${YELLOW}   💰 成本: $0.0004 | ⏱️ 延迟: 0.8s"
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✓ 任务完成 | 累计成本: $0.0008${NC}"
echo ""
echo -e "${GRAY}💡 提示: ReX 自动选择最优 Provider${NC}"
echo ""
echo -e "${GRAY}─────────────────────────────────────────────────────────${NC}"
echo ""
