#!/bin/bash
# 推文配图: 浏览器自动化

echo ""
echo -e "${BG_BLUE}${WHITE}  ReX CLI - 浏览器自动化  ${NC}"
echo ""
echo -e "${GRAY}─────────────────────────────────────────────────────────${NC}"
echo ""
echo -e "${GREEN}➜${NC} ${WHITE}rex run --prompt \"帮我查下最新的AI论文\""
echo ""
echo -e "${CYAN}[Browser]${NC} 🌐 打开 arxiv.org"
echo -e "${CYAN}[Search]${NC} 🔍 'AI agents 2026'"
echo -e "${CYAN}[Scroll]${NC} 📜 加载结果..."
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}  找到 23 篇相关论文:${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  1. ${WHITE}Self-Refining Language Agents${NC}"
echo -e "     ${GRAY}arxiv.org/abs/2601.023 - 156 citations"
echo ""
echo -e "  2. ${WHITE}Context Windows for Long-horizon Tasks${NC}"
echo -e "     ${GRAY}arxiv.org/abs/2602.018 - 89 citations"
echo ""
echo -e "  3. ${WHITE}Tool Use in Open-source Agents${NC}"
echo -e "     ${GRAY}arxiv.org/abs/2601.045 - 67 citations"
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✓ 摘要已保存到: notes/papers.md${NC}"
echo ""
echo -e "${GRAY}─────────────────────────────────────────────────────────${NC}"
echo ""
